### ISSUE TITLE
Does it work for spare point clouds as well?

### ISSUE THREAD

**Issue by GopiRajuMatta** [mrakotosaon/pointcleannet#12]
Hello @mrakotosaon

It's a nice work.

Title and results suggest that well it works for dense point clouds, I couldn't find any information regarding sparse point clouds.

My point cloud data is very sparse, object(Ex: bucket) has 3k points in the point cloud. 
Still is this network work for point cloud denoising?

If not, can you suggest of any modifications that can be done to make it work?

Thank you
Gopi

**Comment by mrakotosaon** [comment]
Hi @GopiRajuMatta 
Thank you for your interest in our work!

For very sparse data I would suggest to retrain the model with similarly sampled data if that is possible?

You could also try to test using our pretrained model but with a larger radius so that you have a more similar number of points per patch to the ones from our dataset. However, it would be highly possible that you end up oversmoothing the details of your point clouds using this approach. 

Best,

Marie-Julie

**Comment by GopiRajuMatta** [comment]
Thank you Marie-Julie for your reply. I will work on your recommendations to get better results.
